version: '3'
volumes:
  money-manager-pg:
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '54321:5432'
    volumes:
      - money-manager-pg:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm install && npm run start:dev"