version: '3'
volumes:
  money-manager-pg-test:
services:
  postgres-test:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '54322:5432'
    volumes:
      - money-manager-pg-test:/var/lib/postgresql/data
